version: v0.0.{build}

branches:
  only:
    - master
    - production
    - /v\d*\.\d*\.\d*/

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - npm install
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build
  - npm run dist

test: off

environment:
  GH_TOKEN: 
    secure: 1Hewqi8gOkLhCGZVhHGj2hZjUyiCRpITSUUyKxRdk3eqedCF1bK18wCNPB+Dbnqn
  DEBUG: electron-builder

configuration:
  - Release

pull_requests:
  do_not_increment_build_number: true

skip_non_tags: true

artifacts:
- path: $(APPVEYOR_PROJECT_NAME)\build\Release
  name: $(APPVEYOR_PROJECT_NAME)-v$(APPVEYOR_REPO_TAG_NAME)

  - provider: Environment
  name: production
  on:
    branch: master # only this will work
    APPVEYOR_REPO_TAG: true # condition will never be evaluated